### ISSUE TITLE
Windows layout scaling renders application unusable

### ISSUE THREAD

**Issue by Thebys** [ridercz/Pooka#1]
Hello, I have significant interest in your application and thank you for making it a reality!

I've tested it and I have a bug to report. Application interface is not usable without significant changes to my environment (display) setup. I use up to date Windows 10 and 4k monitor with some Windows Layout Scaling.

**Expected result**: All interface elements are visible regardless of Windows Layout Scaling.
**Actual result**: Advanced Option and Save button are not visible when Layout scaling is set above 100% (e. g. 125 % or 150 %).

**Steps to reproduce**:

1. Set Windows Layout Scaling to 125 %.
2. Run Pooka.
3. Observe the defect.

Screenshots attached. Tested also with 1920x1080 resolution - same result. Please fix it or guide me a little on how to fix this, I am not very familiar with what could be the cause and fix nor do I have full visual studio.

![pooka_no_scaling_is_ok](https://github.com/ridercz/Pooka/assets/21362158/67d4459e-d8f3-4630-9c65-3d5a2ed0f4b8)
![pooka_with_scaling_bugged](https://github.com/ridercz/Pooka/assets/21362158/4df6a6b9-6fd3-4def-a26f-3a32028bea20)

**Comment by ridercz** [comment]
This solution is not ideal, as it makes controls slightly blurry, but it's good enough for thios type of application where the window isn't actually seen much.
